using System.Text.Json.Nodes;
using Gua.Playtest.Core.Assertions;
using Gua.Playtest.Core.Contracts;
using Xunit;

namespace Gua.Playtest.Contracts.Tests;

public sealed class AssertionTests
{
    private static readonly AssertionOptions Limits = new(10, 1000);
    private static JsonObject Json(string text) => JsonNode.Parse(text)!.AsObject();
    private static EnumCatalogSnapshot Catalog(string members = "\"First\",\"Second\",\"AliasSecond\"")
        => EnumCatalogSnapshot.Create(Json("{\"schemaVersion\":1,\"enums\":[{\"enumType\":\"game.Phase\",\"members\":[" + members + "]}]}"));

    private static JsonObject Assertion(string type, string op, JsonObject? expected = null, double? tolerance = null)
    {
        var result = Json("{\"kind\":\"assertion\",\"quantifier\":\"one\",\"read\":{\"target\":{\"source\":\"world\"},\"region\":\"property\",\"name\":\"value\",\"valueType\":" + type + "},\"operator\":\"" + op + "\"}");
        if (expected is not null) result["expected"] = expected.DeepClone();
        if (tolerance is not null) result["tolerance"] = tolerance;
        return result;
    }
    private static JsonObject Value(string kind, string token, string? element = null)
    {
        var value = Json("{\"type\":\"" + kind + "\",\"value\":" + token + "}");
        if (element is not null) value["elementType"] = element;
        if (kind == "enum" || element == "enum") value["enumType"] = "game.Phase";
        return value;
    }
    private static string TypeOf(JsonObject value)
    {
        var type = value.DeepClone().AsObject(); type.Remove("value"); return type.ToJsonString();
    }

    // Expectations below are literal acceptance examples, never generated by the comparator.
    [Theory]
    [InlineData("integer", "9007199254740991", "9007199254740990", "greaterThan", true)]
    [InlineData("integer", "-9007199254740991", "-9007199254740990", "lessThan", true)]
    [InlineData("integer", "1e0", "1.0", "equals", true)]
    [InlineData("integer", "10.00e-1", "1", "greaterThanOrEqual", true)]
    [InlineData("integer", "-0", "0", "lessThanOrEqual", true)]
    [InlineData("integer", "42", "42", "notEquals", false)]
    [InlineData("number", "-0.0", "0.0", "equals", true)]
    [InlineData("number", "1e-400", "0.0", "equals", true)]
    [InlineData("number", "1e308", "-1e308", "greaterThan", true)]
    [InlineData("number", "2.5", "3.0", "greaterThanOrEqual", false)]
    [InlineData("bool", "true", "false", "notEquals", true)]
    [InlineData("bool", "false", "false", "equals", true)]
    [InlineData("string", "\"é\"", "\"e\\u0301\"", "equals", false)]
    [InlineData("string", "\"A\"", "\"a\"", "equals", false)]
    [InlineData("string", "\"a\\u0000b\"", "\"\\u0000\"", "contains", true)]
    [InlineData("string", "\"猫😀x\"", "\"😀\"", "contains", true)]
    [InlineData("string", "\"猫😀x\"", "\"猫\"", "startsWith", true)]
    [InlineData("string", "\"猫😀x\"", "\"x\"", "endsWith", true)]
    [InlineData("string", "\"abc\"", "\"\"", "contains", true)]
    [InlineData("string", "\"abc\"", "\"b\"", "startsWith", false)]
    [InlineData("string", "\"abc\"", "\"b\"", "endsWith", false)]
    [InlineData("string", "\"abc\"", "\"b\"", "matches", true)]
    [InlineData("string", "\"abc\"", "\"^b$\"", "matches", false)]
    [InlineData("enum", "\"Second\"", "\"AliasSecond\"", "equals", false)]
    [InlineData("enum", "\"Second\"", "\"Second\"", "equals", true)]
    public void ScalarGolden(string kind, string actual, string expected, string op, bool truth)
    {
        var observed = Value(kind, actual);
        var prepared = PreparedAssertion.Create(Assertion(TypeOf(observed), op, Value(kind, expected)), Limits, Catalog());
        Assert.Equal(EvaluationResult.Known(truth), prepared.Evaluate(observed, Catalog()));
    }

    [Theory]
    [InlineData("1.125", "1", 0.125, true)]
    [InlineData("1.125", "1", 0.124, false)]
    [InlineData("1", "1", 0, true)]
    [InlineData("1e308", "-1e308", 1e308, false)]
    public void ApproximationIsInclusiveAbsoluteBinary64Distance(string actual, string expected, double tolerance, bool truth)
    {
        var prepared = PreparedAssertion.Create(Assertion("{\"type\":\"number\"}", "approximatelyEquals", Value("number", expected), tolerance), Limits);
        Assert.Equal(EvaluationResult.Known(truth), prepared.Evaluate(Value("number", actual)));
    }

    [Theory]
    [InlineData("list", "[1,2]", "list", "[2,1]", "equals", false)]
    [InlineData("set", "[1,2]", "set", "[2,1]", "equals", true)]
    [InlineData("set", "[-0,1]", "set", "[1,0]", "notEquals", false)]
    [InlineData("list", "[1,2,3]", "list", "[1,3]", "containsSequence", false)]
    [InlineData("list", "[1,2,3]", "list", "[2,3]", "containsSequence", true)]
    [InlineData("list", "[1,2,3]", "list", "[1,2]", "startsWithSequence", true)]
    [InlineData("list", "[1,2,3]", "list", "[2,3]", "startsWithSequence", false)]
    [InlineData("list", "[1,2,3]", "list", "[2,3]", "endsWithSequence", true)]
    [InlineData("list", "[1,2,3]", "list", "[1,2]", "endsWithSequence", false)]
    [InlineData("list", "[1,1,2]", "list", "[1,1,2]", "sequenceEquals", true)]
    [InlineData("list", "[1,1,2]", "list", "[1,2]", "sequenceEquals", false)]
    [InlineData("list", "[]", "list", "[]", "containsSequence", true)]
    [InlineData("list", "[1]", "list", "[]", "startsWithSequence", true)]
    [InlineData("list", "[1]", "list", "[]", "endsWithSequence", true)]
    [InlineData("list", "[1]", "set", "[]", "containsAll", true)]
    [InlineData("list", "[1]", "list", "[1,1]", "containsAll", true)]
    [InlineData("set", "[1]", "list", "[1,2]", "containsAll", false)]
    [InlineData("set", "[1]", "list", "[2,1,1]", "containsAny", true)]
    [InlineData("list", "[1]", "set", "[]", "containsAny", false)]
    [InlineData("set", "[]", "list", "[1]", "containsAny", false)]
    public void CollectionGolden(string actualKind, string actual, string expectedKind, string expected, string op, bool truth)
    {
        var observed = Value(actualKind, actual, "number");
        var prepared = PreparedAssertion.Create(Assertion(TypeOf(observed), op, Value(expectedKind, expected, "number")), Limits);
        Assert.Equal(EvaluationResult.Known(truth), prepared.Evaluate(observed));
    }

    [Theory]
    [InlineData("contains", "2", true)]
    [InlineData("contains", "4", false)]
    [InlineData("notContains", "2", false)]
    [InlineData("notContains", "4", true)]
    [InlineData("countEquals", "3", true)]
    [InlineData("countNotEquals", "3", false)]
    [InlineData("countGreaterThan", "2", true)]
    [InlineData("countGreaterThanOrEqual", "3e0", true)]
    [InlineData("countLessThan", "3", false)]
    [InlineData("countLessThanOrEqual", "3", true)]
    public void CollectionScalarGolden(string op, string expected, bool truth)
    {
        foreach (var kind in new[] { "list", "set" })
        {
            var observed = Value(kind, "[1,2,3]", "integer");
            var prepared = PreparedAssertion.Create(Assertion(TypeOf(observed), op, Value("integer", expected)), Limits);
            Assert.Equal(EvaluationResult.Known(truth), prepared.Evaluate(observed));
        }
    }

    [Theory]
    [InlineData("[]", "isEmpty", true)]
    [InlineData("[1]", "isEmpty", false)]
    [InlineData("[]", "isNotEmpty", false)]
    [InlineData("[1]", "isNotEmpty", true)]
    public void EmptyGolden(string actual, string op, bool truth)
    {
        foreach (var kind in new[] { "list", "set" })
        {
            var observed = Value(kind, actual, "integer");
            Assert.Equal(EvaluationResult.Known(truth), PreparedAssertion.Create(Assertion(TypeOf(observed), op), Limits).Evaluate(observed));
        }
    }

    public static IEnumerable<object[]> OperatorTypeMatrix()
    {
        // Independent normative allow table, including every scalar and every collection element type.
        string[] universal = ["equals", "notEquals"];
        string[] numeric = ["greaterThan", "greaterThanOrEqual", "lessThan", "lessThanOrEqual"];
        string[] strings = ["contains", "startsWith", "endsWith", "matches"];
        string[] collections = ["contains", "notContains", "containsAll", "containsAny", "isEmpty", "isNotEmpty", "countEquals", "countNotEquals", "countGreaterThan", "countGreaterThanOrEqual", "countLessThan", "countLessThanOrEqual"];
        string[] sequences = ["sequenceEquals", "startsWithSequence", "endsWithSequence", "containsSequence"];
        var ops = universal.Concat(numeric).Concat(strings).Concat(collections).Concat(sequences).Append("approximatelyEquals").Distinct().ToArray();
        foreach (var kind in new[] { "bool", "integer", "number", "string", "enum", "list", "set" })
        foreach (var element in kind is "list" or "set" ? new[] { "bool", "integer", "number", "string", "enum" } : new string?[] { null })
        foreach (var op in ops)
        {
            var allowed = universal.Contains(op) || (kind is "integer" or "number" && numeric.Contains(op))
                || (kind == "number" && op == "approximatelyEquals") || (kind == "string" && strings.Contains(op))
                || (kind is "list" or "set" && collections.Contains(op)) || (kind == "list" && sequences.Contains(op));
            yield return [kind, element!, op, allowed];
        }
    }

    [Theory]
    [MemberData(nameof(OperatorTypeMatrix))]
    public void EveryOperatorTypeCombinationIsAcceptedOrRejected(string kind, string? element, string op, bool allowed)
    {
        static string Token(string kind) => kind switch { "bool" => "true", "integer" or "number" => "1", "enum" => "\"First\"", _ => "\"x\"" };
        var sample = Value(kind, element is null ? Token(kind) : "[" + Token(element) + "]", element);
        JsonObject? expected = op is "isEmpty" or "isNotEmpty" ? null : op.StartsWith("count", StringComparison.Ordinal) ? Value("integer", "1")
            : op is "contains" or "notContains" && element is not null ? Value(element, Token(element)) : sample;
        var config = Assertion(TypeOf(sample), op, expected, op == "approximatelyEquals" ? 0 : null);
        if (allowed)
        {
            var prepared = PreparedAssertion.Create(config, Limits, Catalog());
            Assert.Equal(EvaluationError.None, prepared.Evaluate(sample, Catalog()).Error);
        }
        else Assert.Throws<AssertionConfigurationException>(() => PreparedAssertion.Create(config, Limits, Catalog()));
    }

    [Theory]
    [InlineData("9007199254740992")]
    [InlineData("-9007199254740992")]
    [InlineData("1.00000000000000001")]
    [InlineData("0.999999999999999999999999999999999")]
    [InlineData("1e-400")]
    public void IntegerIsValidatedBeforeRounding(string token)
    {
        var expected = Value("integer", token);
        Assert.Throws<AssertionConfigurationException>(() => PreparedAssertion.Create(Assertion("{\"type\":\"integer\"}", "equals", expected), Limits));
        var prepared = PreparedAssertion.Create(Assertion("{\"type\":\"integer\"}", "notEquals", Value("integer", "1")), Limits);
        Assert.Equal(EvaluationError.ObservationContractViolation, prepared.Evaluate(expected).Error);
    }

    [Fact]
    public void MismatchedTypesAreConfigurationErrorsOrObservationViolations()
    {
        var list = Value("list", "[\"x\"]", "string");
        Assert.Throws<AssertionConfigurationException>(() => PreparedAssertion.Create(Assertion(TypeOf(list), "equals", Value("set", "[\"x\"]", "string")), Limits));
        Assert.Throws<AssertionConfigurationException>(() => PreparedAssertion.Create(Assertion("{\"type\":\"integer\"}", "equals", Value("number", "1")), Limits));
        var prepared = PreparedAssertion.Create(Assertion("{\"type\":\"integer\"}", "notEquals", Value("integer", "1")), Limits);
        Assert.Equal(EvaluationCode.TypeMismatch, prepared.Evaluate(Value("number", "2")).Code);
        Assert.Equal(EvaluationResult.Unknown(EvaluationCode.Missing), prepared.EvaluateUnavailable(EvaluationCode.Missing));
    }

    [Fact]
    public void EnumCollectionsPreserveTypeAndRequireApprovedConsistentCatalogs()
    {
        var list = Value("list", "[]", "enum");
        Assert.Throws<AssertionConfigurationException>(() => PreparedAssertion.Create(Assertion(TypeOf(list), "isEmpty"), Limits));
        var prepared = PreparedAssertion.Create(Assertion(TypeOf(list), "isEmpty"), Limits, Catalog());
        Assert.Equal(EvaluationResult.Known(true), prepared.Evaluate(list, Catalog()));
        Assert.Equal(EvaluationError.ObservationContractViolation, prepared.Evaluate(list).Error);
        Assert.Equal(EvaluationCode.EnumCatalogChanged, prepared.Evaluate(list, Catalog("\"First\",\"Second\"" )).Code);
        var changedType = Value("list", "[]", "enum"); changedType["enumType"] = "other.Phase";
        Assert.Throws<AssertionConfigurationException>(() => PreparedAssertion.Create(Assertion(TypeOf(list), "equals", changedType), Limits, Catalog()));
        foreach (var name in new[] { "Unknown", "1", "First|Second" })
            Assert.Throws<AssertionConfigurationException>(() => PreparedAssertion.Create(Assertion("{\"type\":\"enum\",\"enumType\":\"game.Phase\"}", "equals", Value("enum", "\"" + name + "\"")), Limits, Catalog()));
        var enumList = Value("list", "[\"First\",\"Second\"]", "enum");
        var contains = PreparedAssertion.Create(Assertion(TypeOf(enumList), "contains", Value("enum", "\"Second\"")), Limits, Catalog());
        Assert.Equal(EvaluationResult.Known(true), contains.Evaluate(enumList, Catalog()));
    }

    [Theory]
    [InlineData("number", "[-0,0]")]
    [InlineData("number", "[1,1.0]")]
    [InlineData("integer", "[1,1e0]")]
    [InlineData("string", "[\"x\",\"x\"]")]
    public void DuplicateSetsAreInvalid(string element, string array)
    {
        var set = Value("set", array, element);
        Assert.Throws<AssertionConfigurationException>(() => PreparedAssertion.Create(Assertion(TypeOf(set), "equals", set), Limits));
        var prepared = PreparedAssertion.Create(Assertion(TypeOf(set), "isEmpty"), Limits);
        Assert.Equal(EvaluationError.ObservationContractViolation, prepared.Evaluate(set).Error);
    }

    [Fact]
    public void InvalidRegexAndLimitsFailEagerlyAndTimeoutRemainsUnknown()
    {
        var config = Assertion("{\"type\":\"string\"}", "matches", Value("string", "\"[\""));
        Assert.Equal("RegexInvalid", Assert.Throws<AssertionConfigurationException>(() => PreparedAssertion.Create(config, Limits)).Code);
        config["expected"] = Value("string", "\"abcd\"");
        Assert.Equal("RegexPatternTooLong", Assert.Throws<AssertionConfigurationException>(() => PreparedAssertion.Create(config, new(10, 3))).Code);
        foreach (var limits in new[] { new AssertionOptions(0, 10), new(-1, 10), new(10, 0), new(int.MaxValue, 10) })
            Assert.Throws<AssertionConfigurationException>(() => PreparedAssertion.Create(config, limits));
        config["expected"] = Value("string", "\"^(a+)+$\"");
        var regex = PreparedAssertion.Create(config, new(1, 100));
        var actual = new JsonObject { ["type"] = "string", ["value"] = new string('a', 20000) + "!" };
        Assert.Equal(EvaluationResult.Unknown(EvaluationCode.RegexTimeout), regex.Evaluate(actual)); // real catastrophic-backtracking fault
    }

    [Fact]
    public void PreparedExpectedAndCatalogAreSnapshots()
    {
        var config = Assertion("{\"type\":\"integer\"}", "equals", Value("integer", "1"));
        var prepared = PreparedAssertion.Create(config, Limits);
        config["expected"]!["value"] = 2;
        Assert.Equal(EvaluationResult.Known(true), prepared.Evaluate(Value("integer", "1")));
        var wire = Json("{\"schemaVersion\":1,\"enums\":[{\"enumType\":\"game.Phase\",\"members\":[\"First\"]},{\"enumType\":\"game.Phase\",\"members\":[\"First\"]}]}");
        var snapshot = EnumCatalogSnapshot.Create(wire);
        wire["enums"]![0]!["members"]![0] = "Second";
        var enumPrepared = PreparedAssertion.Create(Assertion("{\"type\":\"enum\",\"enumType\":\"game.Phase\"}", "equals", Value("enum", "\"First\"")), Limits, snapshot);
        Assert.Equal(EvaluationResult.Known(true), enumPrepared.Evaluate(Value("enum", "\"First\""), Catalog("\"First\"")));
        Assert.Equal("EnumConflict", Assert.Throws<AssertionConfigurationException>(() => EnumCatalogSnapshot.Create(wire)).Code);
    }

    [Fact]
    public void MalformedValueAndUnicodeAreNotOrdinaryFalse()
    {
        var prepared = PreparedAssertion.Create(Assertion("{\"type\":\"string\"}", "equals", Value("string", "\"x\"")), Limits);
        foreach (var bad in new[] { Json("{\"type\":\"string\",\"value\":null}"), Json("{\"type\":\"string\",\"value\":\"x\",\"secret\":\"do-not-print\"}"), new JsonObject { ["type"] = "string", ["value"] = "\ud800" } })
            Assert.Equal(EvaluationError.ObservationContractViolation, prepared.Evaluate(bad).Error);
        Assert.Throws<AssertionConfigurationException>(() => PreparedAssertion.Create(Assertion("{\"type\":\"string\"}", "equals", new JsonObject { ["type"] = "string", ["value"] = "\ud800" }), Limits));
    }

    [Fact]
    public async Task StaticLoadingRetainsFiniteBinary64AndExactIntegerWireSemantics()
    {
        var scope = Directory.CreateTempSubdirectory("gua-assertion-static-");
        try
        {
            var scenario = Json(await File.ReadAllTextAsync(Path.Combine(AppContext.BaseDirectory, "fixtures", "scenario.json")));
            scenario["goal"]!["success"] = Assertion("{\"type\":\"number\"}", "approximatelyEquals", Value("number", "1e308"), 1e308);
            var path = Path.Combine(scope.FullName, "scenario.json");
            await File.WriteAllTextAsync(path, scenario.ToJsonString());
            var result = await new StaticContractValidator([scope.FullName]).ValidateFileAsync(path);
            Assert.True(result.IsValid, result.Code);
            var success = Assert.IsType<ScenarioDocument>(result.Document).Goal.Success!;
            Assert.Equal("1e308", success["expected"]!["value"]!.ToJsonString());
            Assert.Equal(EvaluationResult.Known(true), PreparedAssertion.Create(success, Limits).EvaluateJson("{\"type\":\"number\",\"value\":1e308}"));
            scenario["goal"]!["success"] = Assertion("{\"type\":\"integer\"}", "equals", Value("integer", "1.00000000000000001"));
            await File.WriteAllTextAsync(path, scenario.ToJsonString());
            Assert.Equal("IntegerRange", (await new StaticContractValidator([scope.FullName]).ValidateFileAsync(path)).Code);
        }
        finally { scope.Delete(true); }
    }

    [Fact]
    public void RawJsonEntryPointsRejectDuplicatesAndReportSanitizedErrors()
    {
        var config = Assertion("{\"type\":\"integer\"}", "equals", Value("integer", "1")).ToJsonString();
        var prepared = PreparedAssertion.CreateJson(config, Limits);
        Assert.Equal(EvaluationResult.Known(true), prepared.EvaluateJson("{\"type\":\"integer\",\"value\":1e0}"));
        Assert.Equal(EvaluationError.ObservationContractViolation, prepared.EvaluateJson("{\"type\":\"integer\",\"value\":1,\"value\":2}").Error);
        var duplicate = config.Replace("\"value\":1", "\"value\":1,\"value\":2", StringComparison.Ordinal);
        Assert.Equal("DuplicateKey", Assert.Throws<AssertionConfigurationException>(() => PreparedAssertion.CreateJson(duplicate, Limits)).Code);
        var error = Assert.Throws<AssertionConfigurationException>(() => PreparedAssertion.CreateJson("{\"secret-token\":\"do-not-print\"}", Limits));
        Assert.DoesNotContain("do-not-print", error.Message); Assert.DoesNotContain("secret-token", error.Message);
    }
}
